/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AchievementSchema extends BaseModel {
  static $columns = ['color', 'condition', 'description', 'icon', 'id', 'key', 'name', 'xpReward'] as const
  $columns = AchievementSchema.$columns
  @column()
  declare color: string | null
  @column()
  declare condition: string
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare xpReward: number
}

export class AnswerSchema extends BaseModel {
  static $columns = ['answerText', 'answerTrackId', 'gamePlayerId', 'id', 'isCorrect', 'responseMs', 'roundId', 'scoreEarned', 'submittedAt', 'suspiciousFlags', 'userId'] as const
  $columns = AnswerSchema.$columns
  @column()
  declare answerText: string | null
  @column()
  declare answerTrackId: number | null
  @column()
  declare gamePlayerId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCorrect: boolean
  @column()
  declare responseMs: number
  @column()
  declare roundId: number
  @column()
  declare scoreEarned: number
  @column.dateTime()
  declare submittedAt: DateTime
  @column()
  declare suspiciousFlags: string | null
  @column()
  declare userId: number
}

export class FriendshipSchema extends BaseModel {
  static $columns = ['addresseeId', 'createdAt', 'id', 'requesterId', 'status'] as const
  $columns = FriendshipSchema.$columns
  @column()
  declare addresseeId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare requesterId: number
  @column()
  declare status: string
}

export class GamePlayerSchema extends BaseModel {
  static $columns = ['bestStreak', 'correct', 'gameId', 'id', 'incorrect', 'isConnected', 'joinedAt', 'leftAt', 'rank', 'score', 'streak', 'userId', 'xpEarned'] as const
  $columns = GamePlayerSchema.$columns
  @column()
  declare bestStreak: number
  @column()
  declare correct: number
  @column()
  declare gameId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incorrect: number
  @column()
  declare isConnected: boolean
  @column.dateTime()
  declare joinedAt: DateTime
  @column.dateTime()
  declare leftAt: DateTime | null
  @column()
  declare rank: number | null
  @column()
  declare score: number
  @column()
  declare streak: number
  @column()
  declare userId: number
  @column()
  declare xpEarned: number
}

export class GameSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'currentRound', 'decadeFilter', 'difficulty', 'finishedAt', 'genreFilter', 'hostId', 'id', 'maxPlayers', 'mode', 'playlistId', 'publicId', 'roundCount', 'roundDurationMs', 'startedAt', 'status', 'updatedAt', 'winnerId'] as const
  $columns = GameSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentRound: number
  @column()
  declare decadeFilter: string | null
  @column()
  declare difficulty: number
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare genreFilter: string | null
  @column()
  declare hostId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxPlayers: number
  @column()
  declare mode: string
  @column()
  declare playlistId: number | null
  @column()
  declare publicId: string | null
  @column()
  declare roundCount: number
  @column()
  declare roundDurationMs: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerId: number | null
}

export class LeaderboardSnapshotSchema extends BaseModel {
  static $columns = ['computedAt', 'country', 'id', 'period', 'rank', 'score', 'userId'] as const
  $columns = LeaderboardSnapshotSchema.$columns
  @column.dateTime()
  declare computedAt: DateTime
  @column()
  declare country: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare period: string
  @column()
  declare rank: number | null
  @column()
  declare score: bigint | number
  @column()
  declare userId: number
}

export class PlaylistTrackSchema extends BaseModel {
  static $columns = ['id', 'playlistId', 'position', 'trackId'] as const
  $columns = PlaylistTrackSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare playlistId: number
  @column()
  declare position: number | null
  @column()
  declare trackId: number
}

export class PlaylistSchema extends BaseModel {
  static $columns = ['coverUrl', 'createdAt', 'createdBy', 'decade', 'description', 'difficulty', 'genre', 'id', 'isActive', 'isCurated', 'lastSyncedAt', 'name', 'spotifyId', 'trackCount', 'updatedAt'] as const
  $columns = PlaylistSchema.$columns
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column()
  declare decade: string | null
  @column()
  declare description: string | null
  @column()
  declare difficulty: number
  @column()
  declare genre: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isCurated: boolean
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare spotifyId: string | null
  @column()
  declare trackCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfileSchema extends BaseModel {
  static $columns = ['avatarUrl', 'avgResponseMs', 'avgScore', 'bestStreak', 'bio', 'country', 'createdAt', 'favoriteGenres', 'id', 'level', 'totalAnswers', 'totalCorrect', 'totalGames', 'totalWins', 'updatedAt', 'userId', 'username', 'xp', 'xpToNextLevel'] as const
  $columns = ProfileSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare avgResponseMs: number
  @column()
  declare avgScore: number
  @column()
  declare bestStreak: number
  @column()
  declare bio: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare favoriteGenres: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare totalAnswers: number
  @column()
  declare totalCorrect: number
  @column()
  declare totalGames: number
  @column()
  declare totalWins: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare username: string
  @column()
  declare xp: number
  @column()
  declare xpToNextLevel: number
}

export class ReportSchema extends BaseModel {
  static $columns = ['createdAt', 'details', 'gameId', 'id', 'reason', 'reportedId', 'reporterId', 'reviewedBy', 'status'] as const
  $columns = ReportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: string | null
  @column()
  declare gameId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string
  @column()
  declare reportedId: number
  @column()
  declare reporterId: number
  @column()
  declare reviewedBy: number | null
  @column()
  declare status: string
}

export class RoundSchema extends BaseModel {
  static $columns = ['distractors', 'endsAt', 'gameId', 'id', 'revealedAt', 'roundNumber', 'roundToken', 'startsAt', 'trackId'] as const
  $columns = RoundSchema.$columns
  @column()
  declare distractors: string
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare gameId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare revealedAt: DateTime | null
  @column()
  declare roundNumber: number
  @column()
  declare roundToken: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare trackId: number
}

export class TracksCacheSchema extends BaseModel {
  static $columns = ['album', 'artist', 'cachedAt', 'coverUrl', 'durationMs', 'expiresAt', 'genre', 'hasPreview', 'id', 'metadata', 'popularity', 'previewUrl', 'releaseYear', 'spotifyId', 'title'] as const
  $columns = TracksCacheSchema.$columns
  @column()
  declare album: string | null
  @column()
  declare artist: string
  @column.dateTime()
  declare cachedAt: DateTime
  @column()
  declare coverUrl: string | null
  @column()
  declare durationMs: number | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare genre: string | null
  @column()
  declare hasPreview: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: string | null
  @column()
  declare popularity: number | null
  @column()
  declare previewUrl: string | null
  @column()
  declare releaseYear: number | null
  @column()
  declare spotifyId: string
  @column()
  declare title: string
}

export class UserAchievementSchema extends BaseModel {
  static $columns = ['achievementId', 'id', 'unlockedAt', 'userId'] as const
  $columns = UserAchievementSchema.$columns
  @column()
  declare achievementId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare unlockedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['banExpiresAt', 'banReason', 'createdAt', 'email', 'fullName', 'id', 'lastLoginAt', 'lockedUntil', 'loginAttempts', 'password', 'role', 'spotifyAccessToken', 'spotifyId', 'spotifyRefreshToken', 'spotifyTokenExpiresAt', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare banExpiresAt: DateTime | null
  @column()
  declare banReason: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare loginAttempts: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare spotifyAccessToken: string | null
  @column()
  declare spotifyId: string | null
  @column()
  declare spotifyRefreshToken: string | null
  @column.dateTime()
  declare spotifyTokenExpiresAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
